DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'OrderSchema') THEN
        CREATE SCHEMA "OrderSchema";
    END IF;
END $EF$;


CREATE TABLE "OrderSchema"."OrderTypes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_OrderTypes" PRIMARY KEY ("Id")
);


CREATE TABLE "OrderSchema"."Orders" (
    "Id" uuid NOT NULL,
    "Username" text NOT NULL,
    "OrderTypeId" integer NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_OrderTypes_OrderTypeId" FOREIGN KEY ("OrderTypeId") REFERENCES "OrderSchema"."OrderTypes" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_Orders_OrderTypeId" ON "OrderSchema"."Orders" ("OrderTypeId");


