DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'OrderSchema') THEN
        CREATE SCHEMA "OrderSchema";
    END IF;
END $EF$;


CREATE TABLE "OrderSchema"."Order" (
    "Id" uuid NOT NULL,
    "Username" text NOT NULL,
    CONSTRAINT "PK_Order" PRIMARY KEY ("Id")
);


CREATE TABLE "OrderSchema"."OrderType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" uuid NOT NULL,
    "Name" text NOT NULL,
    CONSTRAINT "PK_OrderType" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderType_Order_OrderId" FOREIGN KEY ("OrderId") REFERENCES "OrderSchema"."Order" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_OrderType_OrderId" ON "OrderSchema"."OrderType" ("OrderId");


